### ISSUE TITLE
A bug when querying bdiff using showCnt.perl

### ISSUE THREAD

**Issue by hehao98** [ssc-oscar/lookup#1]
## Steps to replicate

Run the following command on da3 will give the following output

```
bash-4.2$ echo 5ff3b52c89f4813379d8dd9eaefd5aebb248e8f8 | ~/lookup/showCnt.perl bdiff
compressed data corrupted (size mismatch) at /home/audris/lookup/woc.pm line 79, <STDIN> line 1.
```

The content of this commit can be checked [here](https://github.com/fleapx/JavaGuide_view_Interview/commit/5ff3b52c89f4813379d8dd9eaefd5aebb248e8f8)

It seems to be somehow related to the existence of non-ascii characters, but I'm not sure.

**Comment by audrism** [comment]
Pushed fix (no need to decompress).

I think the bulk maps would make more sense using join on c2fbb: see javathruMaps/c2bPkgQjava and javathruMaps/b2cPkgQjava
