### ISSUE TITLE
c2p does not list all associated projects

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#11]
Consider the following:

`echo df6993e7cf7bb752700c861feda483763a115bce | ~/lookup/getValues c2P` gets:
```
df6993e7cf7bb752700c861feda483763a115bce;Kxnrl_System2
```

`echo df6993e7cf7bb752700c861feda483763a115bce | ~/lookup/getValues c2p` gets:
```
df6993e7cf7bb752700c861feda483763a115bce;dordnung_System2
```

Shouldn't `c2p` return all the associated projects which also includes _Kxnrl_System2_?

**Comment by audrism** [comment]
```
echo dordnung_System2 | ~/lookup/getValues p2P
dordnung_System2;popoklopsi_System2

echo Kxnrl_System2 | ~/lookup/getValues p2P
Kxnrl_System2;popoklopsi_System2
```
I.e.,  popoklopsi_System2 is the center project. 

As such, 
echo df6993e7cf7bb752700c861feda483763a115bce | ~/lookup/getValues c2P

should return 
popoklopsi_System2 not Kxnrl_System2

Probably c2P was generated using a slightly different grouping than p2P: I'll investigate

**Comment by audrism** [comment]
fixed p2P and P2p maps. It turns out they were for version R, not S
```
echo Kxnrl_System2 | ~/lookup/getValues P2p
Kxnrl_System2;IntechServers_System2
Kxnrl_System2;JoinedSenses_System2
Kxnrl_System2;Kxnrl_System2
Kxnrl_System2;KyleSanderson_System2
Kxnrl_System2;dordnung_System2
Kxnrl_System2;e54385991_System2
Kxnrl_System2;not1ce111_System2
Kxnrl_System2;popoklopsi_System2
```

**Comment by k----n** [comment]
Thanks!

Is `c2p` supposed to include the results of the `p2P` or `P2p` maps?

**Comment by audrism** [comment]
c2P is a composition of c2p | p2P

c2p represents raw data

**Comment by k----n** [comment]
Ok, what does the `c2p` raw data exactly represent?

I was under the impression that it would be all projects containing the commit.

When I look at the commit, it appears that it originally appeared in the fork here: https://github.com/Kxnrl/System2/commit/df6993e7cf7bb752700c861feda483763a115bce
From a pull request here: https://github.com/Kxnrl/System2/pull/1

And does not appear associated with any of the other projects e.g.:
https://github.com/dordnung/System2/commit/df6993e7cf7bb752700c861feda483763a115bce
https://github.com/KyleSanderson/System2/commit/df6993e7cf7bb752700c861feda483763a115bce

So if `df6993e7cf7bb752700c861feda483763a115bce` exists only in `Kxnrl_System2`, shouldn't `c2p` return `Kxnrl_System2` only?

**Comment by audrism** [comment]
> I was under the impression that it would be all projects containing the commit.

Correct.

P, however, represents many projects linked via shared commits. 

so if c is in a and a is in group labeled by project A, then  c will be considered in commits from group A

**Comment by audrism** [comment]
If it helps, entities in P are labels for groups. The labels match one actual repo from the group, but they do not represent that repo but all repos in the group

**Comment by k----n** [comment]
When you refer to groups, do you mean a project and its forks?

If a project is forked, is there any circumstance where it may not be in a p2P or P2p mapping?

**Comment by audrism** [comment]
- Groups are not derived from github forks (see https://dl.acm.org/doi/10.1145/3379597.3387499 and https://github.com/ssc-oscar/forks

- Groups are Leuven communities on repo to commit graph 

> If a project is forked, is there any circumstance where it may not be in a p2P or P2p mapping?
Not entirely sure what it means, but if 
a repo is gh fork (and is in WoC collection) it will be likely to be grouped with other forks/clones

p2P (and p2c)  should list all repos in WoC, so if p it is not in in, it  will not be in WoC.

**Comment by audrism** [comment]
The version S  of project metadata has some useful info (it should be finished in a couple of days):

db.proj_metadata.S.findOne()
{
        "_id" : ObjectId("5fd397520e50a7ed55f7f216"),
        "FileInfo" : {
                "other" : 16,
                "JavaScript" : 13
        },
        "numStars" : 8,
        "NumAuthors" : 11,
        "NumBlobs" : 205,
        "LatestCommitDate" : 1502653273,
        "projectID" : "0----0_d-struct",
        "EarlistCommitDate" : 1401495076,
        "rootFork" : "ysgard_d-struct",
        "communitySize" : 11,
        "NumCommits" : 143,
        "NumFiles" : 29
}
Specifically, it gives github's version of root fork if available. Root for a for means traversing to the point when repo is not a fork.

**Comment by k----n** [comment]
@audrism Any idea why there might be only `79118039` entries?

```
> mongo --host "da1.eecs.utk.edu"

mongos> use WoC
switched to db WoC

mongos> db.proj_metadata.S.count()
79118039
```

In the summary https://bitbucket.org/swsc/overview/src/master/ it's suggested that there are `135162320` projects.

**Comment by audrism** [comment]
These are Ps, so all the data from associated p's is collected in a single place

**Comment by k----n** [comment]
Thanks, are all the possible keys for the collection documented somewhere?

**Comment by audrism** [comment]
The documentation is implicit in lookup/README.md as the decision what to include is still undecided. data input to  prjToMongo.perl involves capturing the date range (P2tspanFullS$i.gz) and various stats (P2summFullS$i.s). 

One thing that still needs improvement is the upper date range

**Comment by audrism** [comment]
The specific lines in lookup/prjSummary.perl:
```
for my $p (keys %{$d{c}}){
  my $stars = defined $d{s}{$p} ? $d{s}{$p} : "";
  my $forks = defined $d{f}{$p} ? scalar (keys %{$d{f}{$p}}) : 0;
  my $parent = defined $d{parent}{$p} ? $d{parent}{$p} : "";
  my $as = defined $d{P2a}{$p} ?  $d{P2a}{$p} : "";
  my $fs = defined $d{P2f}{$p} ?  $d{P2f}{$p} : "";
  my $bs = defined $d{P2b}{$p} ?  $d{P2b}{$p} : "";
  print "$p;$parent;$stars;$forks;$d{p}{$p};$d{c}{$p};$as;$bs;$fs";
  for my $e (keys %{$d{e}{$p}}){
    print ";$e=$d{e}{$p}{$e}";
  }
```

**Comment by k----n** [comment]
For reference, I was able to get these keys from ~2million projects:

- 'numForks'
- 'projectID'
- 'NumAuthors'
- 'numStars'
- 'LatestCommitDate'
- 'rootFork'
- 'communitySize'
- 'NumBlobs'
- 'NumCommits'
- 'FileInfo'
- 'NumFiles'
- 'EarlistCommitDate'

So it looks the example here https://github.com/ssc-oscar/lookup/issues/11#issuecomment-743295208 has everything except `numForks `.

**Comment by audrism** [comment]
communitySize is the number of repos in the deforeked project

**Comment by k----n** [comment]
@audrism Is communitySize the count of P2p determined by the Louvain community detection?

I'm confused about numForks:
```
{ "_id" : ObjectId("5fd39a49ea4b6c7aa40df75a"), "FileInfo" : { "Python" : 1213, "Rust" : 3, "other" : 614, "Sql" : 7, "C/C++" : 11, "JavaScript" : 12 }, "NumAuthors" : 17, "numForks" : 1, "NumBlobs" : 19835, "LatestCommitDate" : NumberLong("4410614298"), "projectID" : "chris17453_ddb", "EarlistCommitDate" : 1543409360, "communitySize" : 1, "NumCommits" : 8210, "NumFiles" : 1860 }
```

For the `chris17453_ddb` project, it doesn't appear that there is a fork on github?
https://github.com/chris17453/ddb/network/members

**Comment by audrism** [comment]
Srry, the files prjSummary and prjToMongo were obsolete. Updated now

**Comment by audrism** [comment]
As for chris17453_ddb, the fork information is in prjSummary.perl: reads from some amalgamation of somewhat recent ghTorrent data + some additional queries. Since this is external data, it is not clear how often it might be updated.

**Comment by k----n** [comment]
@audrism It seems like some P data is still missing in mongo?

E.g. `zzhi_JobEngine`
```
getValues:
> echo zzhi_JobEngine | getValues P2p
zzhi_JobEngine;zzhi_JobEngine

Mongo:
> use WoC
> db.proj_metadata.S.find({'projectID': 'zzhi_JobEngine'})
```

The repository still exists: https://github.com/zzhi/JobEngine

**Comment by audrism** [comment]
Very odd records before and after are present (I can drop and reimport the entire proj_metadata.S, perhaps 
the record was dropped bu some user):

```
zcat P2summFullS4.s | grep -B1 -A1 zzhi_JobEngine
abpostman1_apps;;;0;1;8;1;136;156;other=134;PHP=17;JavaScript=5
zzhi_JobEngine;;;1;1;3;2;625;629;other=134;Sql=15;TypeScript=27;JavaScript=453
LittleOrange23_vue-basic;;;0;1;7;2;57;58;other=37;JavaScript=21
da3:/data/basemaps/gz>fg
mongo --host=da1
mongos> db.proj_metadata.S.find({'projectID': 'abpostman1_apps'})
{ "_id" : ObjectId("5fd399ab9942967727c62140"), "FileInfo" : { "other" : 134, "PHP" : 17, "JavaScript" : 5 }, "NumAuthors" : 1, "NumBlobs" : 136, "LatestCommitDate" : 1560964733, "projectID" : "abpostman1_apps", "EarlistCommitDate" : 1560946518, "communitySize" : 1, "NumCommits" : 8, "NumFiles" : 156 }
mongos> db.proj_metadata.S.find({'projectID': 'LittleOrange23_vue-basic'})
{ "_id" : ObjectId("5fd399969942967727c0ee60"), "FileInfo" : { "other" : 37, "JavaScript" : 21 }, "NumAuthors" : 2, "NumBlobs" : 57, "LatestCommitDate" : 1544497507, "projectID" : "LittleOrange23_vue-basic", "EarlistCommitDate" : 1543799174, "communitySize" : 1, "NumCommits" : 7, "NumFiles" : 58 }
```

**Comment by k----n** [comment]
Thanks @audrism for looking into this.

Yes please reimport, that'd probably be best.

I also noticed that there wasn't an index for projectID, so I created it.
I'm not sure if you want to add access control on mongo, but if you do could you create this index?
```
mongos> db.proj_metadata.S.createIndex({"projectID": 1})
```

**Comment by k----n** [comment]
There's also been some odd results (maybe I'm misinterpreting NumFIles):

```
>zcat P2summFullS*.s | grep 'aukeys_php-demo'
aukeys_php-demo;;;0;1;1;1;1717;

mongos> db.proj_metadata.S.find({'projectID': 'aukeys_php-demo'})
{ "_id" : ObjectId("5fe4eed83e247ea24d69c619"), "NumAuthors" : 1, "NumBlobs" : 1717, "LatestCommitDate" : 1557194385, "projectID" : "aukeys_php-demo", "EarlistCommitDate" : 1557194385, "communitySize" : 1, "NumCommits" : 1, "NumFiles" : 0 }
```

There seems to be many files in the repo?

Repo: https://github.com/aukeys/php-demo

**Comment by audrism** [comment]
numFiles counts all unique pathnames over the entire history of the project. Some repos may have tens of millions of files

**Comment by k----n** [comment]
Okay, so shouldn't there be 1732 filepaths for `aukeys_php-demo`?

I assume it's the count of the `P2f` mapping?

The c2f of the only commit in that repo returns the all the filepaths:
```
> echo 830f3046ce6ad6f750b1342a340717354da899f9 | getValues -f c2f | wc -l
1732
```

**Comment by audrism** [comment]
1. It counts from 0, so for the actual number add 1 

2. No key P2f  for aukeys_php-demo may be due to the fact that there is no parent for the commit, will need to add this in the next version

3. echo 68c646e1b5ac4bf45d688af4ae38c7cca8ef20d6 | ~/lookup/getValues -f c2f |wc
12

**Comment by audrism** [comment]
- Fixed db.proj_metadata.S: it was dropping last partial batch for import

- added index for projectID and AuthorID in auth_metadata.S
some authors were too big to index, so they have been removed:
db.auth_metadata.S.remove( { AuthorID: {$exists: true}, $where: "this.AuthorID.length > 10000"} )
WriteResult({ "nRemoved" : 10 })

- It appears I will need to regenerate P2f, however, so that may affect on the entire db.proj_metadata.S

**Comment by k----n** [comment]
Thanks! Happy Holidays!

It looks like some projects still aren't getting added, e.g.
```
> zcat P2summFullS*.s | grep 'pentesterwtf_docker-bazel-buildkite'
pentesterwtf_docker-bazel-buildkite;;;0;1;6;1;9;4;other=4

mongos> db.proj_metadata.S.find({'projectID': 'pentesterwtf_docker-bazel-buildkite'})

```

**Comment by audrism** [comment]
Marry Christmas!

This is one of these no-commit projects. The commit is listed, but the content of the commit is missing

**Comment by k----n** [comment]
What is a no-commit project?

This is what I see when I map the commits to file and blob:
```
>echo pentesterwtf_docker-bazel-buildkite | getValues -f P2c | cut -d\; -f2 | getValues c2f
1d1cdacb5e965ecab36bdf2e30a1104b36c445ac;Dockerfile
2578f08b20000f805c34e8a7251548ee15120bf4;Dockerfile;README.md
4734686df0e4ed785d60fa1a9cdf5f82cea86d6c;Dockerfile
bae561bf64a58791b2a73db708d7f1ce44115481;Dockerfile
daf243ba7e86c0d34bb967dc5fdf1f25f9faeba9;Dockerfile
e901d26604c16344352869be4abf4aa144e10a9d;Dockerfile;bazel.sh;buildkite-agent.cfg

>echo pentesterwtf_docker-bazel-buildkite | getValues -f P2c | cut -d\; -f2 | getValues c2b
1d1cdacb5e965ecab36bdf2e30a1104b36c445ac;9c33e16eb4dff6c31ae916fe069a8ac15de55c16
2578f08b20000f805c34e8a7251548ee15120bf4;108c92f241818aa3ba9516a9cbdfc693b35fb131;98a001aec19bb51cf0c543f8244b416b4dbbf951
4734686df0e4ed785d60fa1a9cdf5f82cea86d6c;7a7c57c4488112bffbb5de3e26ac70eebb622679
bae561bf64a58791b2a73db708d7f1ce44115481;deef2bea9498c888a8af5b517aa0d6ff1442643c
daf243ba7e86c0d34bb967dc5fdf1f25f9faeba9;7f3e8170c5d6375e2ef2bb4ed856b07513dafffa
e901d26604c16344352869be4abf4aa144e10a9d;0861ab4f0256b32f2451df44dfb1e578cde4c4de;0d214872e2214d1466b8dab4c7bedb591ab058d4;f6ef8d059f5cf2de7f59e7db3060393e188355af
```

**Comment by audrism** [comment]
None of the commits have valid  author timestamps in this project

**Comment by k----n** [comment]
> None of the commits have valid author timestamps in this project

Thanks, `echo pentesterwtf_docker-bazel-buildkite | getValues -f P2c | cut -d\; -f2 | getValues c2ta` all produce timestamps of `0000000000`.

**Comment by k----n** [comment]
Why is the author timestamp considered and not the committer timestamp?

It looks like the commits of `pentesterwtf_docker-bazel-buildkite` has valid committer timestamps.

It seems like the author timestamp might have been messed up because of using this: https://github.com/google/copybara
but the committer timestamp is valid.

**Comment by audrism** [comment]
The interesting event (in most cases) is when the commit was authored, not committed. Correcting destroyed time stamp would remove that semantic (assuming the committer/author/tool followed it). It may be worth doing correctiion in cases when commit and authorship are close in time.
