### ISSUE TITLE
Some lookups in fast folder still R?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#12]
It looks like depending on the server some lookups defer to the R version since the map exists in the fast folder when you are trying to lookup something in the S version.

Is this supposed to happen?

**Comment by audrism** [comment]
Correct, since updating maps takes some time, the updates are done incrementally. Currently only ctags token-related maps are on version R, the rest is on v S

**Comment by k----n** [comment]
Ok, it seems like lookups are still happening for maps like `c2P` are still on `version R` when looking up on `da3` because the map is in the `fast` folder?

**Comment by audrism** [comment]
Fixed in 0e567c47ca362f7a37b730738d3462e57e95f95d
