### ISSUE TITLE
Blobs are missing?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#14]
For example:

`echo 0001f9fcc01ec8019657cfbc249e1a99f087908a | showCnt blob` was run with the output:
```
no blob 0001f9fcc01ec8019657cfbc249e1a99f087908a in 0
```

There is a `b2c` mapping:
```
> echo 007966799d926dc238dca635e2fe80df6e0b48e0 | getValues b2c

007966799d926dc238dca635e2fe80df6e0b48e0;d1f2d24001d1e42a0f926e4f8555015caba07848
```

The commit `d1f2d24001d1e42a0f926e4f8555015caba07848` links to these 2 commits:
* https://github.com/vapor-camp/harmony-examples/commit/d1f2d24001d1e42a0f926e4f8555015caba07848
* https://github.com/ether-camp/harmony-examples/commit/d1f2d24001d1e42a0f926e4f8555015caba07848

**Comment by audrism** [comment]
Only text blobs are currently stored. What is "text" is defined by git. 

A small fraction of text blobs may be missing, due to processing pipline (as with commits)

**Comment by k----n** [comment]
Thanks.

Is "text" the files where the line changes can be determined?

It seems like git either treats a file as text or binary?
https://stackoverflow.com/questions/6855712/why-does-git-treat-this-text-file-as-a-binary-file

Is there a better way to determine the type of blob instead of changing the file and running `git diff`?

**Comment by audrism** [comment]
in a fork of libgit2 I have created classify command that determines the type of object: but you need an original git repo to use it. libgit2 probably has the actual algorithm (that probably relies on file name and content) to determine git definition of "binary"

**Comment by k----n** [comment]
Neat, looks like it's a function in the libgit2 library: https://libgit2.org/libgit2/#HEAD/group/blob/git_blob_is_binary

And was called in places like:
* https://bitbucket.org/swsc/git/src/ef32d42adf9a317b7eae76e3ab49f47202d4c43e/grabfc.c#lines-36
* https://bitbucket.org/swsc/git/src/ef32d42adf9a317b7eae76e3ab49f47202d4c43e/grabf.c#lines-8
