### ISSUE TITLE
Strange Error Message for "showCnt blob"

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#16]
When you try `echo c227083464fb9af8955c90d2924774ee50abb547 showCnt blob`, the result is:
```
Error: , msg=66;12332038717;c227083464fb9af8955c90d2924774ee50abb547, code=0
Error: , 66;12332038717;c227083464fb9af8955c90d2924774ee50abb547, 0
```

When you try `echo e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 showCnt blob`, the result is:
```
Error: , msg=102;12511082764;e69de29bb2d1d6434b8b29ae775ad8c2e48c5391, code=
Error: , 102;12511082764;e69de29bb2d1d6434b8b29ae775ad8c2e48c5391, 
```

**Comment by k----n** [comment]
It seems like the blobs were not retrieved because they linked to too many commits maybe?

```
> echo c227083464fb9af8955c90d2924774ee50abb547 | getValues b2c | tr ";" "\n" | wc -l
108452

> echo e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 | getValues b2c | tr ";" "\n" | wc -l
51856611
```

It also seems like the `showCnt blob` exits with code 0 as well as opposed to when no blob exists which uses a different exit code.

**Comment by k----n** [comment]
Interesting... it looks like `e69de29bb2d1d6434b8b29ae775ad8c2e48c5391` is a 0 byte binary file (according to github).

So the code might be exiting with 0 since the blob copied has no data but the error is because of printing with perl?

**Comment by audrism** [comment]
There are a bunch of odd blobs/trees"
grep e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 ~/lookup/*.pm
/home/audris/lookup/woc.pm:  "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391" => 7826798, #\n 

You can see some other odballs there as well.
