### ISSUE TITLE
Identifying Project Source

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#19]
Are these the sources for projects?:
https://github.com/ssc-oscar/lookup/blob/c9c51f011a6ed254e1de4220fbca7fef6230c5a0/fixP1.perl#L10-L31

If nothing is prepended to a project, then can it only be a github project?

**Comment by audrism** [comment]
Correct. There may be unfixed exceptions that still need to be fixed, however

**Comment by k----n** [comment]
There seem to be new ones like `sourceforge.net`, where would you find an updated source list?

**Comment by audrism** [comment]
These mappings were used to go to new (present) schema that is much simpler:
if github: replace the first  _ with / and prepend https://github.com/
else replace the first two _ with / and prepend https://

**Comment by k----n** [comment]
It seems like there's some sources here too: https://github.com/ssc-oscar/lookup/blob/4a9ceed1e7429be83284bf946aa54f3854a55b0f/README.md?plain=1#L1755

What would be the best way to check if github or not, without querying github?

**Comment by audrism** [comment]
non-GH project contains . or /, while GH does not
