### ISSUE TITLE
showCnt blob format does not match README

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#2]
Looks like a line got commented out here https://github.com/ssc-oscar/lookup/blob/9fcf2e9722cc538106d3740f2e5314eb4f7234ef/showCnt.perl#L103

Not sure if it's supposed to be commented out?

**Comment by audrism** [comment]
Its not backwards compatible, but after much discussion it was decided that b default showCnt should only display the actual content and no metadata. If you need metadata/headers to separate output from different requests, it needs to be enabled

**Comment by k----n** [comment]
Documentation fixed in 98e9aaee0c0f47f02049de40cd291fd393e9515d
