### ISSUE TITLE
Ties for c2P?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#21]
It seems like I came across a unique situation where a commit has 2 P:
```
> echo 0a661380d1c6ec9c030bff10fbf70ce48ec1411e | getValues -f c2P
0a661380d1c6ec9c030bff10fbf70ce48ec1411e;0-T-0_docker
0a661380d1c6ec9c030bff10fbf70ce48ec1411e;00312049_gcc
```

Is this supposed to happen?

Edit: I guess a better question is, does this mean this commit belongs to 2 "independent" project clusters?
Does this happen because a repo was cloned but the clone projects have diverged so much that the projects can be now considered independent?

**Comment by k----n** [comment]
Here's an example with 4:
```
> echo 2564268f996dfb94ea2f0d1f776208bec63f6312 | getValues -f c2P
2564268f996dfb94ea2f0d1f776208bec63f6312;0-T-0_ps4-linux
2564268f996dfb94ea2f0d1f776208bec63f6312;00ERNEST00_FFmpeg
2564268f996dfb94ea2f0d1f776208bec63f6312;00onebook_u-boot
2564268f996dfb94ea2f0d1f776208bec63f6312;0emanresuym_motioneyeos
```

**Comment by audrism** [comment]
Yes, community detection eliminates spurious links. That commit is an example of such link
