### ISSUE TITLE
showCnt.perl no longer works

### ISSUE THREAD

**Issue by dlomax64** [ssc-oscar/lookup#26]
@audrism It seems like a file that showCnt uses either no longer exists, or has been moved. Anytime I try to use it I get 'cant open /fast/All.sha1c/commit_0.tch'. The website utilizes showCnt heavily, so most of it's functionality also does not work currently.

**Comment by audrism** [comment]
Thank you for noticing: da4 rebooted to replace raid battery and the ssds with lookup tables were not remounted
Fixed now

**Comment by dlomax64** [comment]
Thanks!

**Comment by dlomax64** [comment]
Having this problem again now with mostShared. Gives the error: `can't open /fast/All.sha1c/tree_0.tch`

**Comment by audrism** [comment]
On which server?

**Comment by dlomax64** [comment]
I'm on da0. It worked yesterday

**Comment by audrism** [comment]
added ssh to da5 and pushed to lookup

**Comment by dlomax64** [comment]
Now I'm getting `ssh: connect to host da5 port 22: Connection refused`

**Comment by audrism** [comment]
added -p443, should work now.

**Comment by dlomax64** [comment]
Works now, but I'm getting `ECDSA host key for IP address '192.168.12.5' not in list of known hosts.` after every entry that it returns. That seems like a problem on my end though

**Comment by audrism** [comment]
ssh to da5 manually and ssh will add the host key for you. 

you can also change da5 to da4

**Comment by dlomax64** [comment]
Alright, thanks for fixing it
