### ISSUE TITLE
Problems with mostWidelyUsed

### ISSUE THREAD

**Issue by dlomax64** [ssc-oscar/lookup#28]
Every time I use mostWidelyUsed.sh it returns the same 10 blobs no matter what project I use.

e69de29bb2d1d6434b8b29ae775ad8c2e48c5391;22557224
3c3629e647f5ddf82548912e337bea9826b434af;1761602
f1250e584c94b80208b61cf7cae29db8e486a5c7;1167827
261eeb9e9f8b2b4b0d119366dda99c6fd7d35c64;1117335
ee27ba4b4412b0e4a05af5e3d8a005bc6681fdf3;1115712
cc4dba29d959a2da7b97f9edd3c7c91384b2ee5b;1073088
2559e841b02edfdc128176bfbdc0b938209a99ea;1035673
b512c09d476623ff4bf8d0d63c29b784925dbdf8;1030362
f1d0f13c8a54d0f8d78f86a1f9348f3c59750694;974164
432d1aeb01df666910230893f78e0d1ee7635a61;913696

**Comment by audrism** [comment]
Hmm, got slightly different results:
```bash
~/lookup/mostWidelyUsed.sh bairdko_swiftbrew
e69de29bb2d1d6434b8b29ae775ad8c2e48c5391;22557224
8b137891791fe96927ad78e64b0aad7bded08bdc;3960138
94a25f7f4cb416c083d265558da75d457237d671;3053308
4d29575de80483b005c29bfcac5061cd2f45313e;1764745
3c3629e647f5ddf82548912e337bea9826b434af;1761602
5008ddfcf53c02e82d7eee2e57c38e5672ef89f6;1703087
6b60c1042f58d9fabb75485aa3624dddcf633b5c;1652127
a11777cc471a4344702741ab1c8a588998b1311a;1452271
b1c56658557b8162aa9f5ba8610ed03a5e558d9d;1365816
dea3013d6710ee273f49ac606a65d5211d480c88;1364470
da3:/da5_data/home/audris/update/T>~/lookup/mostWidelyUsed.sh claudey_sooperb  
e69de29bb2d1d6434b8b29ae775ad8c2e48c5391;22557224
3c3629e647f5ddf82548912e337bea9826b434af;1761602
f1250e584c94b80208b61cf7cae29db8e486a5c7;1167827
261eeb9e9f8b2b4b0d119366dda99c6fd7d35c64;1117335
ee27ba4b4412b0e4a05af5e3d8a005bc6681fdf3;1115712
cc4dba29d959a2da7b97f9edd3c7c91384b2ee5b;1073088
2559e841b02edfdc128176bfbdc0b938209a99ea;1035673
b512c09d476623ff4bf8d0d63c29b784925dbdf8;1030362
f1d0f13c8a54d0f8d78f86a1f9348f3c59750694;974164
432d1aeb01df666910230893f78e0d1ee7635a61;913696
```

These blobs are everywhere

**Comment by dlomax64** [comment]
Okay, I see now. I think I saw a few that were the same and assumed they were all  like that. Thanks
