### ISSUE TITLE
Is c2f and c2b supposed to be 1-1?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#3]
I run `echo 62355f7076fe3a8a7e40880957f3c1fef9d7e35c | ~/lookup/getValues c2f` and get 14 values

I run `echo 62355f7076fe3a8a7e40880957f3c1fef9d7e35c | ~/lookup/getValues c2b` and get 8 values

It seems like most c2f and c2b have the same amount of values, but sometimes they are not the same.

I imagine that the amount of blobs and files should be the same for a commit.

**Comment by k----n** [comment]
Commit that I am looking up: https://github.com/gephi/gephi/commit/62355f7076fe3a8a7e40880957f3c1fef9d7e35c

Looks like there are 13 files.

**Comment by audrism** [comment]
b is blob: two distinct files may share it (have the same content). nfiles >= nblobs

**Comment by k----n** [comment]
> b is blob: two distinct files may share it (have the same content). nfiles >= nblobs

Thanks! Really appreciate it.
