### ISSUE TITLE
Problem with getNeighbors

### ISSUE THREAD

**Issue by dlomax64** [ssc-oscar/lookup#34]
I am getting an `Use of uninitialized value $v` error anytime I run the getNeighbors script. 
![image](https://user-images.githubusercontent.com/53716031/128526180-8db4a5f6-fc95-4918-8229-18e4ec60ccad.png)

**Comment by audrism** [comment]
I changed getNeighors.perl, please pull and check (swsc/lookup)

**Comment by dlomax64** [comment]
That fixed it
