### ISSUE TITLE
Available S version (.s) maps?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#4]
From the tutorial:
_(.s) signifies that there are either .s or .gz versions of these files in gz/ subfolder, which can be opened with Python gzip module or Unix zcat.  
da0 is the only server with these .s/.gz files_  

List of relationships:
```
* a2b 		* a2c (.s)	* a2f		* a2ft		
* a2p (.s)	* a2trp0 (.s)
* b2a		* b2c (.s)	* b2f (.s)	* b2ob		* b2tk
* c2b (.s)	* c2cc		* c2f (.s)	* c2h		* c2pc
* c2p (.s)	* c2P		* c2ta (.s)	* c2td
* f2a		* f2b (.s)	* f2c (.s)		
* p2a (.s)	* p2c (.s)	* P2c
* td2c		* td2f
```

It seems like there aren't that many S version maps described in the list of relationships?

**Comment by audrism** [comment]
The single server does not have sufficient disk space for all, so the search pattern should be 
/da?_data/basemaps/gz

**Comment by k----n** [comment]
Thanks, I noticed that there are only S versions for c2p, a2c, p2c, c2ta.

What are the differences between versions R and S?

Also I can't find anything with `trp` (Torvalds Path?) in the gz subfolder.

What's the difference between `b2callfFull` vs `b2cFull`? 
`b2fextra` vs `b2fFull`?

**Comment by audrism** [comment]
As I move to new version, I archive older versions due to limited space on the servers.

see bitbucket.org/swsc/overview about versions


TP was calculated for some old version of data, I am not sure its that relevant.

b2callfFull breaks files by commit, while b2fFull lists files and b2cFull commits

b2fExtra may be a leftover of some consistency check.

**Comment by k----n** [comment]
Very nice, thanks!

How long does it take to generate the gzip maps?

Also the `WoCFse19.pdf` FSE'19 Keynote is 0 bytes in bitbucket.org/swsc/overview .

**Comment by k----n** [comment]
FSE'19 slides are here: https://esec-fse19.ut.ee/wp-content/uploads/2019/08/WoCFse19.pdf .

**Comment by audrism** [comment]
I pushed the slides in case fse site goes out at some point

MRS paper extension to EMSE should have the time durations, but I think it is still under review
