### ISSUE TITLE
S database for commits?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#6]
I ran `cut -d\; -f4 /da4_data/data/All.blobs/commit_*.idx | wc -l` which has 2034176272 commits.

According to https://bitbucket.org/swsc/overview/src/master/README.md that is the amount of commits for version R.

So where can I find version S?

**Comment by audrism** [comment]
newest cmts/trees are on da3. I am updating da4. 
Given that new blobs in vS take over 30TB increasing the overall size to over 150TB, so reshuffling over servers will be needed

**Comment by k----n** [comment]
Thanks
