### ISSUE TITLE
a2ft, a2b, a2trp0, P2c, td2f maps not working?

### ISSUE THREAD

**Issue by k----n** [ssc-oscar/lookup#8]
When I try:

```
echo "Audris Mockus <audris@utk.edu>" | ~/lookup/getValues a2ft
echo "Adam Tutko <atutko@vols.utk.edu>" | ~/lookup/getValues a2ft
```

I get tie errors:
```
tie error for /da0_data/basemaps/a2ftFullR.0.tch
tie error for /da0_data/basemaps/a2ftFullR.1.tch
tie error for /da0_data/basemaps/a2ftFullR.2.tch
tie error for /da0_data/basemaps/a2ftFullR.3.tch
tie error for /da0_data/basemaps/a2ftFullR.4.tch
tie error for /da0_data/basemaps/a2ftFullR.5.tch
tie error for /da0_data/basemaps/a2ftFullR.6.tch
tie error for /da0_data/basemaps/a2ftFullR.7.tch
tie error for /da0_data/basemaps/a2ftFullR.8.tch
tie error for /da0_data/basemaps/a2ftFullR.9.tch
tie error for /da0_data/basemaps/a2ftFullR.10.tch
tie error for /da0_data/basemaps/a2ftFullR.11.tch
tie error for /da0_data/basemaps/a2ftFullR.12.tch
tie error for /da0_data/basemaps/a2ftFullR.13.tch
tie error for /da0_data/basemaps/a2ftFullR.14.tch
tie error for /da0_data/basemaps/a2ftFullR.15.tch
tie error for /da0_data/basemaps/a2ftFullR.16.tch
tie error for /da0_data/basemaps/a2ftFullR.17.tch
tie error for /da0_data/basemaps/a2ftFullR.18.tch
tie error for /da0_data/basemaps/a2ftFullR.19.tch
tie error for /da0_data/basemaps/a2ftFullR.20.tch
tie error for /da0_data/basemaps/a2ftFullR.21.tch
tie error for /da0_data/basemaps/a2ftFullR.22.tch
tie error for /da0_data/basemaps/a2ftFullR.23.tch
tie error for /da0_data/basemaps/a2ftFullR.24.tch
tie error for /da0_data/basemaps/a2ftFullR.25.tch
tie error for /da0_data/basemaps/a2ftFullR.26.tch
tie error for /da0_data/basemaps/a2ftFullR.27.tch
tie error for /da0_data/basemaps/a2ftFullR.28.tch
tie error for /da0_data/basemaps/a2ftFullR.29.tch
tie error for /da0_data/basemaps/a2ftFullR.30.tch
tie error for /da0_data/basemaps/a2ftFullR.31.tch
```

**Comment by k----n** [comment]
Same for a2b, a2trp0.

It also seems like I can't get any hits for `~/lookup/getValues P2c`, it seems unlikely that I wouldn't have any hits for the values I tried since it is from the R map.

When I run `echo "7c3482ec5b6a963ad28f781ef5fcd0fecbb9649d" | ~/lookup/getValues td2f`, I get:
```
compressed data corrupted (size mismatch) at /home/audris/lookup/cmt.pm line 467, <STDIN> line 1.
```

**Comment by audrism** [comment]
* echo Floyag_learngit2 | ~/lookup/getValues P2c            
Floyag_learngit2;24f006888821c14865e3e71011bae0dcad643aba

* Pushed fix for td2f (files are not compressed)

* what is a2ft? there is a2f

**Comment by k----n** [comment]
Thanks.

I pulled the latest repo and P2c and c2P works now.

I also got confused about P2c because `echo "f0c2bcdc750ff68d8b3ff40f9d1e729117ba45ba" | ~/lookup/getValues c2P` was originally producing the incorrect output. e.g.
```
> echo "f0c2bcdc750ff68d8b3ff40f9d1e729117ba45ba" | ~/lookup/getValues c2P
f0c2bcdc750ff68d8b3ff40f9d1e729117ba45ba;007373632d6f736361725f6c6f6f6b7570
```

I got `a2ft` from the tutorial here: https://github.com/woc-hack/tutorial/blob/master/README.md
Is it a typo?

**Comment by k----n** [comment]
P.S. the description of this repo has a typo and is not linking to https://bitbucket.org/swsc/lookup

**Comment by audrism** [comment]
I think that was an example of how you might create your own databases, not something that is supported by the infrastructure

**Comment by k----n** [comment]
Ok thanks. I think it might've just been a typo since `ft` isn't even a key here: https://github.com/woc-hack/tutorial/blob/master/README.md#0-31tch-files-in-databasemaps-on-da0-and-fast-on-da5
